name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'web/**'
      - 'package.json' # ルートの依存関係変更も検知
      - 'nx.json'      # Nx 設定変更も検知
      - '.github/workflows/ci.yaml'

jobs:
  lint:
    name: Lint Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # プロジェクトで使用するバージョンに合わせて調整

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        # with:
          # bun-version: latest # 必要に応じてバージョン指定

      - name: Install dependencies
        run: bun install

      - name: Run Backend Lint
        run: ./nx lint backend

      - name: Run Frontend Lint
        run: ./nx lint web
        # Note: 必要に応じて format check や type check 用のタスクを Nx で実行
        # run: ./nx format web --check
        # run: ./nx typecheck web
