name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'web/**'
      - '.github/workflows/ci.yaml'

jobs:
  lint-backend:
    name: Lint Backend (Go)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # プロジェクトで使用するバージョンに合わせて調整

      # golangci-lint のインストールと実行
      # (golangci-lint の設定ファイル .golangci.yml が backend ディレクトリにある想定)
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59 # 使用するバージョンを指定
          working-directory: backend
          # オプション: キャッシュを有効にする場合
          # cache: true

  lint-frontend:
    name: Lint Frontend (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # bun のセットアップ
      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        # with:
          # bun-version: latest # 必要に応じてバージョン指定

      - name: Install dependencies
        run: bun install

      # Lint (ESLint/Prettier) の実行
      # package.json に lint スクリプトがある想定
      # 例: "lint": "eslint . && prettier --check ."
      # もしくは typecheck スクリプトに含める
      - name: Run Biome Lint
        run: bun run lint
      - name: Run Biome Format Check
        run: bun run format:check
      # 必要であれば typecheck も残す
      - name: Run Type Check
        run: bun run typecheck
        # run: bun run lint # もし lint スクリプトがあれば
